<!doctype html>
<html>
<head>
  <title>SAREPO - Search results</title>
  <meta name="keywords" content="SAREPO, sarepo">
  <meta name="description" content="SAREPO is a bash script which creates a Slackware ARM local mirror repository. This SAREPO theme is an Apache mod_autoindex fancyindexing front-end for viewing the local mirror repository in a browser.">
  <meta name="abstract" content="SAREPO theme for Apache mod_autoindex fancyindexing.">
  <meta name="author" content="Penthux.NET"> 
  <meta name="publisher" content="Penthux.NET">
  <meta name="copyright" content="Penthux.NET 2021-<?php echo date("Y"); ?>">
  <meta name="version" content="1.0.2-EIIR">
  <meta name="generator" content="Penthux.NET php">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="creation-date" content="Thu, 08 Sep 2022 13:48:35 UTC">
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta http-equiv="content-type" content="application/html;charset=UTF-8">
  <meta http-equiv="content-style-type" content="text/css">
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>
  <link rel="stylesheet" type="text/css" href="/slackwarearm/.sarepo/sarepo_theme.css">
  <link rel="icon" href="/slackwarearm/.sarepo/favicon.ico">
  <link rel="shortcut icon" href="/slackwarearm/.sarepo/favicon.ico">
</head>
<body>  
	